version: 0
metadata:
  name: Buildbot Bridge Task Graph
  description: Buildbot Bridge
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "bhearsum/python-test-runner"
      command:
        - "/bin/bash"
        - "-c"
        - "checkout-pull-request && tox -e py27"
    extra:
      github:
        env: true
        events:
          - push
          - pull_request.*
    metadata:
      name: Buildbot Bridge Pull Request
      description: Pull Request
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
