language: python

python:
    - "2.7"

install:
    - sudo apt-add-repository -y ppa:travis-ci/sqlite3
    - sudo apt-get update
    - sudo apt-get install sqlite3
    - travis_retry pip install tox==1.8

script:
    - tox -e py27

after_success:
    - tox -e py27-coveralls
